repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: 9a9bbc0
    hooks:
      - id: clang-format
        name: clang-format
        args: [--style=file]  # uses .clang-format

  # - repo: https://github.com/pocc/pre-commit-hooks
  #   rev: 9a9bbc0
  #   hooks:
  #     - id: clang-tidy
  #       args: [--config-file=.clang-tidy]  # uses .clang-tidy
  #       fail: false